### ISSUE TITLE
Error when undefined value arrives

### ISSUE THREAD

**Issue by ellenaua** [PolymerElements/gold-zip-input#27]
Uncaught TypeError: Cannot read property 'replace' of undefined
https://github.com/PolymerElements/gold-zip-input/blob/master/gold-zip-input.html#L128

Similar problem was in gold-phone-input but there it's fixed already https://github.com/PolymerElements/gold-phone-input/issues/37

**Comment by notwaldorf** [comment]
Thanks a lot for filing this issue! Would you be interested in writing a patch for this?

**Comment by samuelli** [comment]
Fixed in https://github.com/PolymerElements/gold-zip-input/commit/abd83bdef97161a4cd8649abde7668af6609779f

**Comment by kf6nux** [comment]
I'm not sure that was the correct solution as it replaces Number type `0` with empty string and still causes a null pointer dereference if it's Number type and truthy.  Thoughts?

**Comment by kf6nux** [comment]
The above PR simply typecasts the value to String to prevent null dereference when calling String methods.

**Comment by samuelli** [comment]
This issue can be closed.

@kf6nux: that isn't possible. For input, value is always a string (already typecasted).
```
$ $0.value = 0
0
$ $0.value
"0"
$ value = "0"
"0"
$ value = value ? value.replace(/-/g, '') : '';
"0"
```

**Comment by kf6nux** [comment]
@samuelli It is possible if `value` is set by `Polymer.Base.set()`.

In your example, this would look like: 

> $0.set('value',  123)
> VM187 gold-zip-input.html:125 Uncaught TypeError: this.value.charAt is not a function(…)

**Comment by samuelli** [comment]
@kf6nux: Good call, here's a jsbin http://jsbin.com/kahafusufo/edit?html,js,output
@notwaldorf: can you please take a look at their PR?
