### ISSUE TITLE
Changed event does not fire

### ISSUE THREAD

**Issue by admwx7** [PolymerElements/gold-zip-input#38]
### Description
When performing a user input the change event is never fired

### Expected outcome

'change' event is fired when user make a change to the input field

### Actual outcome

no event is fired

### Steps to reproduce
1. Input element
2. Change value field

### Browsers Affected
- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by admwx7** [comment]
@notwaldorf you've got the most commits on this repo, figured you'd be the best bet on taking a look, posted a PR that contains the fix as used by paper-input directly, feedback?

**Comment by notwaldorf** [comment]
Reviewed! Just left a comment asking for a test :)

**Comment by dman777** [comment]
I just hit this issue myself. Any ETA when the fix  will be merged?

**Comment by admwx7** [comment]
Yeah, that's my bad, life... Just need to add a test, going to try to throw it in this week.
